### ISSUE TITLE
Use Redis-OM HashModel for product vectors.

### ISSUE THREAD

**Issue by Spartee** [Spartee/redis-vector-search#2]
### Description

Currently the demo app does not use Redis-om-python for the product vectors. Instead, it just sets the vectors with ``Redis.hset`` with the related product key generated by the redis-om-models defined in ``models.py``. While these are very similar, using Redis-om-python ``HashModel`` will simplify the codebase quite a bit.

### Related code

in ``load_data.py``. This function is what reads the data from the json files and stores them with the generated pk for the json document that corresponds to that vector.

```python
def set_product_vectors(product_vectors, redis_conn, products_with_pk):
    # TODO use redis-om HasHModel for product vectors
    # sort products with pk by value of product_id
    products_with_pk.sort(key=lambda x: x.product_id)
    product_vectors.sort(key=lambda x: x["product_id"])

    for product, product_pk in zip(product_vectors, products_with_pk):
        key = "product_vector:" + str(product["product_id"])
        redis_conn.hset(key,
                        mapping={
                            "product_pk": product_pk.pk,
                            "product_id": product["product_id"],

                            # Add tag fields to vectors for hybrid search
                            "gender": product_pk.product_metadata.gender,
                            "category": product_pk.product_metadata.master_category,

                            # add image and text vectors as blobs
                            "img_vector": np.array(product["img_vector"], dtype=np.float32).tobytes(),
                            "text_vector": np.array(product["text_vector"], dtype=np.float32).tobytes()
                            })

```

### Implementation

**Option 1**
 - [x] Implement a new ``HashModel`` class in ``models.py`` for product vectors.
 - [x] Use that model in ``load_data.py``
 - [ ] Make product vector loading async
 - [x] Replace hget calls in ``routes.py`` with redis-om-python retrievals (async)

**Option 2**
- [ ] Implement ``Product`` and ``ProductMetadata`` as ``HashModel`` classes
- [ ] Make sure vectors are added to the schema in ``load_data.py`` and that all async loading works as expected.
- [ ] Make API routes use the HashModel class for all retrieval and vector search calls.

**Comment by tylerhutcherson** [comment]
Created https://github.com/redis/redis-om-python/issues/343

**Comment by tylerhutcherson** [comment]
Closing this in favor of a future port to RedisVL.
